baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Polis Paralela"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
disableKinds = ["taxonomyTerm"]
[Taxonomies]
category = "thinks/categories"
[permalinks]
  categories = "thinks/categories/:slug/"